version: "3"
services:
  mysql:
    container_name: mysql_service
    hostname: mysql_service
    ports:
      - "3306:3306"
    image: "mysql:8.4"
    environment:
      - MYSQL_DATABASE=dataset
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data/mysql_volume:/var/lib/mysql

  datamart:
    container_name: datamart_service
    image: "datamart:v1"
    ports:
      - '9000:9000'
    volumes:
      - shared:/shared
    depends_on:
      - mysql

  spark:
    container_name: spark_app
    image: "spark:v1"
    volumes:
      - shared:/shared
      - ./configs:/configs
    depends_on:
      - mysql
      - datamart

volumes:
  shared: