version: "3"
services:
  mysql:
    container_name: mysql-service
    hostname: mysqlservice
    ports:
      - "3306:3306"
    image: "mysql:8.4"
    environment:
      - MYSQL_DATABASE=dataset
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ../mysql_volume:/var/lib/mysql

  datamart:
    container_name: datamart-service
    image: "datamart:v1"
    ports:
      - '9000:9000'
    volumes:
      - shared:/shared
      - ./datamart_libs:/root
    depends_on:
      - mysql

  spark:
    container_name: spark-app
    image: "spark:v1"
    volumes:
      - shared:/shared
    depends_on:
      - mysql
      - datamart

volumes:
  shared: