apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configs-pvc
  labels:
    type: local-configs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      configs: local