apiVersion: v1
kind: PersistentVolume
metadata:
  name: configs-pv
  labels:
    configs: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/dzigen/Desktop/ITMO/sem2/BigData/Лабы/lab8/configs"