apiVersion: v1
kind: Pod
metadata:
  name: datamart
  labels:
    app: datamart
spec:
  containers:
  - name: datamart
    image: "datamart:v1"
    resources: 
      requests: 
        memory: "4Gi"
        cpu: "1"
      limits:
        memory: "8Gi"
        cpu: "2"
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
      readOnly: false
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: shared-pvc