apiVersion: v1
kind: Pod
metadata:
  name: model-pod
  labels:
    app: model
spec:
  containers:
  - name: model
    image: "spark:v1"
    resources: 
      requests: 
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "8Gi"
        cpu: "4"
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
      readOnly: false
    - name: configs-volume
      mountPath: /configs
      readOnly: false
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: shared-pvc
  - name: configs-volume
    persistentVolumeClaim:
      claimName: configs-pvc