apiVersion: v1
kind: Pod
metadata:
  name: model-pod
  labels:
    app: model
spec:
  containers:
  - name: model
    image: "my_spark:v1"
    resources: 
      requests: 
        memory: "8Gi"
        cpu: "2"
      limits:
        memory: "16Gi"
        cpu: "4"
    volumeMounts:
    - mountPath: /shared
      name: shared-volume
      readOnly: false
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: shared-pvc