apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql_deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.4
        resources: 
          requests: 
            memory: "5Gi"
            cpu: "0.5"
          limits:
            memory: "10Gi"
            cpu: "1"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql_secret
              key: mysql_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql_secret
              key: mysql_database
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql_volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql_volume
        persistentVolumeClaim:
          claimName: mysql_pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql_service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306