apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql_pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/dzigen/Desktop/ITMO/sem2/BigData/Лабы/lab8/data/mysql_volume