apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    mysql: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/dzigen/Desktop/ITMO/sem2/BigData/Лабы/mysql_volume/"