apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql_pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local_mysql