apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared_pv
  labels:
    type: local_shared
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/shared/