apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
  labels:
    type: local-shared
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/dzigen/Desktop/ITMO/sem2/BigData/Лабы/shared/"